plugins {
    id 'fabric-loom' version '1.7.4'
}

version = "1.1.0"
group = "com.podiumextra"

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21" 
    mappings "net.fabricmc:yarn:1.21+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.15.11"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    // Ensures the bytecode is compatible with Java 21
    it.options.release = 21
}
